---
title: "R Notebook"
author: "Kiki Kanik"
output: html_notebook
---
##Problem 0
```{r}
gmp <- read.table("gmp.dat")
gmp$pop <- round(gmp$gmp/gmp$pcgmp)
```

##Problem 1
```{r}
plot(pcgmp~pop, data=gmp, xlab="Population", 
  ylab="$/person-year",
  main="US Metropolitan Areas, 2006",
  pch = 16, cex = 0.5)

curve(6611*x^(1/8),add=TRUE,col="blue")
curve(6611*x^(1/9),add=TRUE,col="yellow")
curve(6611*x^(1/10),add=TRUE,col="green")
```
##Problem 2
```{r}
mse <- function(para, N = gmp$pop, Y = gmp$pcgmp){
  #' this is a header comment explaining what the funcion does. 
  #' the function takes in arguments para, N, and Y. 
  #' @return the mean of the data sets
  return(mean((Y - para[1]*N^para[2])^2))
  }
mse(c(6611,0.15))
mse(c(5000,0.10))
```

##Problem 3
  #quantity par shows us "the best set of parameters found." Par is basically just short for parameters. We need to put in or set a defualt for the best parameters for our problem
  #quantity value means "the value of the function corresponding to par." basically, what our entire optim evaluated to. 
```{r}
optim(c(y0=6611,a=1/8), mse, method = "BFGS")
optim(c(y0=6718,a=1/9), mse, method = "BFGS")
optim(c(y0=6223,a=1/10), mse, method = "BFGS")
```

##Problem 4
```{r}
plm <- function(y0, N = gmp$pop, Y = gmp$pcgmp) {
  #' this function takes in args y0, N and Y
  #' @param ol
  #' @param rl 
  #' @param returns rl, values of each vector
  ol <- optim(c(y0), mse, method = "BFGS")
  rl <- list(y0 = ol$par[1], a=ol$par[2], msevalue=ol$value)
  return(rl)
}
plm(c(6611,0.15))
plm(c(5000,0.10))
```

##Problem 5
```{r}
gmp_2013 <- read.csv("gmp-2013.dat")
plm(c(6611,1/8), N = gmp_2013$pop, Y = gmp_2013$pcgmp)
```

